####################
ARG ALPINE_VERSION=latest

FROM alpine:$ALPINE_VERSION
WORKDIR /scripts

ARG NODE_VERSION=latest
ARG VERSION=latest

ENV NODE_ENV=production
ENV PACKAGE_MANAGERS=yarn,npm

# RUN apk add --update nodejs~=$NODE_VERSION yarn
RUN apk add --update nodejs yarn

RUN mkdir /my-tags && \
    echo -e '- echo: Welcome to ymlr container' > /scripts/index.yaml
RUN yarn global add ymlr@$VERSION

ENTRYPOINT ["ymlr", "--tag-dirs", "/my-tags", "--"]
CMD ["/scripts/index.yaml", ""]
