####################
ARG BUN_VERSION=alpine

FROM oven/bun:$BUN_VERSION
WORKDIR /scripts

ARG VERSION=latest

ENV NODE_ENV=production
ENV PACKAGE_MANAGERS=bun,yarn,npm
ENV OPTIMIZE_MODE=best

RUN bunx ymlr@$VERSION -v
RUN mkdir /my-tags && \
    echo '- echo: Welcome to ymlr container' > /scripts/index.yaml

ENTRYPOINT ["bunx", "--bun", "ymlr", "--tag-dirs", "/my-tags", "--"]
CMD ["/scripts/index.yaml", ""]
