####################
ARG BUN_VERSION=alpine

FROM oven/bun:$BUN_VERSION
WORKDIR /scripts
RUN apk add --no-cache --update tzdata

ARG VERSION=latest

ENV NODE_ENV=production
ENV PACKAGE_MANAGERS=bun

RUN mkdir /my-tags && \
    echo '- echo: Welcome to ymlr container' > /scripts/index.yaml

RUN cd /usr/local/lib && \
    bun add ymlr@$VERSION

ENTRYPOINT ["bun", "run", "/usr/local/lib/node_modules/ymlr/bin/cli.js", "--tag-dirs", "/my-tags", "--"]
CMD ["/scripts/index.yaml", ""]
