# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  push:
    branches:    
      - '**'
    paths:
      - src/**
      - package.json
      - tsconfig.*
jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENV_STAGE }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn ci:test

      - name: Create a new tag
        run: yarn ci:tag
        env:
          GITHUBTOKEN: ${{ secrets.GIT_TOKEN }}
          LASTCOMMITSHA: ${{ github.SHA }}
